wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    code_path: code/code/Train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.8
    start_time: 1670074591.818621
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.10.8
      5: 0.13.5
      8:
      - 2
      - 5
adaptive:
  desc: null
  value: true
batch_size:
  desc: null
  value: 128
depth:
  desc: null
  value: 16
dropout:
  desc: null
  value: 0.0
epochs:
  desc: null
  value: 200
gamma:
  desc: null
  value: 0.1
label_smoothing:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.1
momentum:
  desc: null
  value: 0.9
opt:
  desc: null
  value: sam
rho:
  desc: null
  value: 0.05
suffix:
  desc: null
  value: null
threads:
  desc: null
  value: 20
uid:
  desc: null
  value: 2hc23hwm
wandb:
  desc: null
  value: online
weight_decay:
  desc: null
  value: 0.0005
width_factor:
  desc: null
  value: 8
