name: overparameterization
program: OverParameterizedRegression.py
project: NNSAM
method: grid
parameters:
  seed:
    values: [0, 1, 2]
  wandb:
    value: online
  opt:
    values: ["sgd", "sam", "nnsam"]
  rho:
    values: [.01, .02, .05, .1, .2, .5]
  lr:
    value: .01
  num_steps:
    value: 20000
  weight_decay:
    values: [.001, .01, .1]
  suffix:
    value: CROSS-VALIDATION
  train_ex:
    value: 1000
  val_ex:
    value: 100
  test_ex:
    value: 100
  x_dim:
    value: 1201
  y_dim:
    value: 6
  noise_std_frac:
    value: .01
  
