name: overparameterization (non-stochastic)
program: OverParameterizedRegression.py
project: NNSAM
method: grid
parameters:
  seed:
    values: [0]
  wandb:
    value: online
  opt:
    values: ["sgd", "sam", "nnsam"]
  rho:
    values: [0, .1, .2]
  lr:
    value: .01
  num_steps:
    value: 2000
  weight_decay:
    value: .01
  suffix:
    value: CROSS-VALIDATION_III
  train_ex:
    value: 1000
  val_ex:
    value: 100
  test_ex:
    value: 10000
  x_dim:
    value: 1201
  y_dim:
    value: 6
  noise_std_frac:
    value: .01
  eval_iter:
    value: 100
  log_iter:
    value: 100
  full_batch:
    value: 1
  
