name: sgd
program: Train.py
project: MomentumSAM
method: grid
parameters:
  wandb:
    value: online
  opt:
    value: sgd
  lr:
    value: .1
  epochs:
    value: 400
  seed:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  suffix:
    value: ALL_DATA
